# Generated by Django 5.2 on 2026-10-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='usuario',
        ),
    ]
